// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package portDomain

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PortDomainClient is the client API for PortDomain service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PortDomainClient interface {
	RecordPort(ctx context.Context, opts ...grpc.CallOption) (PortDomain_RecordPortClient, error)
	FindPort(ctx context.Context, in *FindPortParams, opts ...grpc.CallOption) (*Port, error)
}

type portDomainClient struct {
	cc grpc.ClientConnInterface
}

func NewPortDomainClient(cc grpc.ClientConnInterface) PortDomainClient {
	return &portDomainClient{cc}
}

func (c *portDomainClient) RecordPort(ctx context.Context, opts ...grpc.CallOption) (PortDomain_RecordPortClient, error) {
	stream, err := c.cc.NewStream(ctx, &PortDomain_ServiceDesc.Streams[0], "/portDomain.PortDomain/RecordPort", opts...)
	if err != nil {
		return nil, err
	}
	x := &portDomainRecordPortClient{stream}
	return x, nil
}

type PortDomain_RecordPortClient interface {
	Send(*Port) error
	CloseAndRecv() (*RecordPortStats, error)
	grpc.ClientStream
}

type portDomainRecordPortClient struct {
	grpc.ClientStream
}

func (x *portDomainRecordPortClient) Send(m *Port) error {
	return x.ClientStream.SendMsg(m)
}

func (x *portDomainRecordPortClient) CloseAndRecv() (*RecordPortStats, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(RecordPortStats)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *portDomainClient) FindPort(ctx context.Context, in *FindPortParams, opts ...grpc.CallOption) (*Port, error) {
	out := new(Port)
	err := c.cc.Invoke(ctx, "/portDomain.PortDomain/FindPort", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PortDomainServer is the server API for PortDomain service.
// All implementations must embed UnimplementedPortDomainServer
// for forward compatibility
type PortDomainServer interface {
	RecordPort(PortDomain_RecordPortServer) error
	FindPort(context.Context, *FindPortParams) (*Port, error)
	mustEmbedUnimplementedPortDomainServer()
}

// UnimplementedPortDomainServer must be embedded to have forward compatible implementations.
type UnimplementedPortDomainServer struct {
}

func (UnimplementedPortDomainServer) RecordPort(PortDomain_RecordPortServer) error {
	return status.Errorf(codes.Unimplemented, "method RecordPort not implemented")
}
func (UnimplementedPortDomainServer) FindPort(context.Context, *FindPortParams) (*Port, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindPort not implemented")
}
func (UnimplementedPortDomainServer) mustEmbedUnimplementedPortDomainServer() {}

// UnsafePortDomainServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PortDomainServer will
// result in compilation errors.
type UnsafePortDomainServer interface {
	mustEmbedUnimplementedPortDomainServer()
}

func RegisterPortDomainServer(s grpc.ServiceRegistrar, srv PortDomainServer) {
	s.RegisterService(&PortDomain_ServiceDesc, srv)
}

func _PortDomain_RecordPort_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PortDomainServer).RecordPort(&portDomainRecordPortServer{stream})
}

type PortDomain_RecordPortServer interface {
	SendAndClose(*RecordPortStats) error
	Recv() (*Port, error)
	grpc.ServerStream
}

type portDomainRecordPortServer struct {
	grpc.ServerStream
}

func (x *portDomainRecordPortServer) SendAndClose(m *RecordPortStats) error {
	return x.ServerStream.SendMsg(m)
}

func (x *portDomainRecordPortServer) Recv() (*Port, error) {
	m := new(Port)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PortDomain_FindPort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindPortParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortDomainServer).FindPort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/portDomain.PortDomain/FindPort",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortDomainServer).FindPort(ctx, req.(*FindPortParams))
	}
	return interceptor(ctx, in, info, handler)
}

// PortDomain_ServiceDesc is the grpc.ServiceDesc for PortDomain service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PortDomain_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "portDomain.PortDomain",
	HandlerType: (*PortDomainServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindPort",
			Handler:    _PortDomain_FindPort_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RecordPort",
			Handler:       _PortDomain_RecordPort_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "PortDomainService.proto",
}
